### ISSUE TITLE
Ability for the user to ignore an error code in the future (not displayed)

### ISSUE THREAD

**Issue by vgravelNeosoft** [NeosoftTechnologiesInc/Error-Dialog#10]
The user could have the ability to check a '**ignore this error code in the future**' box. If an error with the same error code occurs, it would not be displayed again. The Error-Dialog VI would be keeping a list of error code to not be displayed.

**Comment by NeosoftDKim** [comment]
- Add the boolean
![image](https://github.com/NeosoftTechnologiesInc/Error-Dialog/assets/149504000/c6ffdfb9-cb8e-4985-b5e1-cf636fe39c7c)

- Add ignore step when being initialized
![image](https://github.com/NeosoftTechnologiesInc/Error-Dialog/assets/149504000/cf2b8c8f-b54a-468f-b5b5-5616fef18c04)

- Implement Ignore step
![image](https://github.com/NeosoftTechnologiesInc/Error-Dialog/assets/149504000/c98b98ff-c4f3-4abf-944c-15bb27ed7cf4)

- Modify exit to add ignore code
![image](https://github.com/NeosoftTechnologiesInc/Error-Dialog/assets/149504000/1f3100ba-386b-4e60-8a01-5a065fa830b9)
