### ISSUE TITLE
Remove Stop LabVIEW call in EXIT case

### ISSUE THREAD

**Issue by ThatsTheEnd** [NeosoftTechnologiesInc/Error-Dialog#11]
Hi Dev Team,
I really liked your approach with a useful error dialogue.
Unfortunately, I have to admit that I lost an hour debugging why my application would not exit correctly until I removed this toolkits error display.
is there a reason why you would end labview?
![image](https://user-images.githubusercontent.com/66672184/211600789-8093e326-24ff-49c6-b56f-8d57347f3a8c.png)
Cheers,
Niko

**Comment by CyGaNeo** [comment]
Hi Niko,
Sorry about that !
We were trying to avoid the auto error handling to send another popup if the output of the VI is not connected.
We didn't realized tht it was stopping the whole caller.
A new version is ready to be released with new features and this bug will be removed !

Stay tuned !

**Comment by brouffet** [comment]
Fix in the version 1.1.0
