### ISSUE TITLE
During full screen screenshot, the file selection popup appears in the screenshot and hides the error itself

### ISSUE THREAD

**Issue by vgravelNeosoft** [NeosoftTechnologiesInc/Error-Dialog#15]
During full screen screenshot, the file selection popup appears in the screenshot and hides the error itself as shown here:

![image](https://github.com/NeosoftTechnologiesInc/Error-Dialog/assets/118299095/82f07157-f93e-4cf8-8fe4-b498a67839dc)

**Comment by CyGaNeo** [comment]
Is this fixed ? Can we close the issue?
