### ISSUE TITLE
Tip string for error screenshot is wrong

### ISSUE THREAD

**Issue by vgravelNeosoft** [NeosoftTechnologiesInc/Error-Dialog#16]
When hoovering over the camera icon to take a screenshot of the error, the tip string shown is wrong (it's the same as the search ni.com button).

**Comment by NeosoftDKim** [comment]
![image](https://github.com/NeosoftTechnologiesInc/Error-Dialog/assets/149504000/f70c562b-b595-4e8e-96c1-e34cba8f3f0d)

Change the description and tip strip for the camera icon

**Comment by CyGaNeo** [comment]
Is this fixed ? Can we close it ?
